### PR TITLE
Update gem to not use any Rails specific code

### LINKED ISSUE #14: Add Sinatra support
I love this gem and would love to add it to a Sinatra app as well. Is there any reason this is Rails specific? It seems to me like we could plug a similar middleware into Sinatra with little issue.

Would this be possible within this gem or easier to achieve with a new gem?

### PR DESCRIPTION
**Pull request by cbetta**
- Replaced `starts_with?` with the Ruby native `start_with?`
- Replaced `present?` with `!= nil`
- Replaced `presence` with the literal implementation from the Rails codebase

With these changes I've been able to successfully deploy a Sinatra app.

Closes #14

### CODE REVIEW

**Comment by jalada** [comment]
Thanks for this @cbetta. Sorry I haven't had a chance to review recently, I will try to soon :)

**Comment by cbetta** [comment]
@jalada how is that review coming?

**Comment by jalada** [comment]
Thanks @cbetta! I made some syntax tweaks but otherwise all good. Your contribution is much appreciated. I made [an example app](https://github.com/pixielabs/letsencrypt-rails-heroku-sinatra-example) for others using Sinatra to show the steps you need to take, as there are a couple of places you have to add `LetsEncrypt.configure` and load in the rake tasks. Hope that helps! :)

**Comment by cbetta** [comment]
Thanks @jalada! FYI I already shipped this to Flow2: https://github.com/peterc/flow2/pull/9 which is a Sinatra app :)

**Pull request closed without merging**
